### ISSUE TITLE
no reorder on collection sort

### ISSUE THREAD

**Issue by pwmckenna** [rotundasoftware/backbone.collectionView#55]
it would be nice to be able to sort the underlying collection and have the view be updated to reflect the new order. happy to help with pull requests if that would be helpful.

**Comment by dgbeck** [comment]
Hi @pwmckenna ! Thanks for the feedback! Can you be more specific about what behavior you are looking for w/ code examples? What you describe sounds like something that must already be supported, but hard to say for sure - clarification would be helpful. Thx!

**Comment by pwmckenna** [comment]
Wow, great response time. Thanks! Ok, here goes:

On the example page http://rotundasoftware.github.io/backbone.collectionView, I set a breakpoint where the views are being created, then call `singleSelectionView.collection.sortBy('firstName')` after the view has been rendered. The views didn't reorder themselves (though I don't see anything in the code to suggest that they would).

![screen shot 2015-01-02 at 11 02 07 am](https://cloud.githubusercontent.com/assets/295678/5598663/21ecef7e-926f-11e4-9e71-65c3cc46ef28.png)
![screen shot 2015-01-02 at 11 02 50 am](https://cloud.githubusercontent.com/assets/295678/5598664/21ede17c-926f-11e4-936d-7a11eb277ebf.png)


If they did reorder I'd expect John to be at the top of the list.

**Comment by dgbeck** [comment]
> Wow, great response time.

=)  We try our best.

The collection view should be re-rendering itself due to its [listener on the `sort` event](https://github.com/rotundasoftware/backbone.collectionView/blob/master/src/backbone.collectionView.js#L514-L517) from the collection. Can you see why `render` is not being called or behaving as expected?

**Comment by pwmckenna** [comment]
ah! the library itself does do exactly what I was hoping for. the issue is that the examples page (gh-pages) was last updated 2 years ago, which presumably pre-dates the sorting support. anyhow, i'm all set, thanks!

**Comment by dgbeck** [comment]
Wow, time flies!
