### ISSUE TITLE
collection not initializated by default

### ISSUE THREAD

**Issue by patrixd** [rotundasoftware/backbone.collectionView#57]
I'm having problems using your lastest version because it does not initialize the collection instance by default. The version 0.8.2 did and my code is not compatible with the new version because of that at the moment. 

Also I saw a code that I think is not a good practice in BackboneJS.
```
initializationOptions : [
			{ "collection" : new Backbone.Collection() },
			{ "modelView" : null },
			{ "modelViewOptions" : {} },
			{ "itemTemplate" : null },
			{ "itemTemplateFunction" : null },
			{ "selectable" : true },
			{ "clickToSelect" : true },
			{ "selectableModelsFilter" : null },
			{ "visibleModelsFilter" : null },
			{ "sortableModelsFilter" : null },
			{ "selectMultiple" : false },
			{ "clickToToggle" : false },
			{ "processKeyEvents" : true },
			{ "sortable" : false },
			{ "sortableOptions" : null },
			{ "reuseModelViews" : true },
			{ "detachedRendering" : false },
			{ "emptyListCaption" : null }
		],
```
It is not recommended to initialize any object there, beacuase the objects will be shared between diferent instances of collectionView. Maybe you should use that initialization options inside of a function.
```
initializationOptions : function () { 
        return [
			{ "collection" : new Backbone.Collection() },
			{ "modelView" : null },
			{ "modelViewOptions" : {} },
			{ "itemTemplate" : null },
			{ "itemTemplateFunction" : null },
			{ "selectable" : true },
			{ "clickToSelect" : true },
			{ "selectableModelsFilter" : null },
			{ "visibleModelsFilter" : null },
			{ "sortableModelsFilter" : null },
			{ "selectMultiple" : false },
			{ "clickToToggle" : false },
			{ "processKeyEvents" : true },
			{ "sortable" : false },
			{ "sortableOptions" : null },
			{ "reuseModelViews" : true },
			{ "detachedRendering" : false },
			{ "emptyListCaption" : null }
		]; },
```

**Comment by dgbeck** [comment]
Hi @patrixd !

> it does not initialize the collection instance by default

Can you be more explicit about what has changed / cite the line(s) of code?

> It is not recommended to initialize any object there, beacuase the objects will be shared between diferent instances of collectionView. Maybe you should use that initialization options inside of a function.

Yes this looks wrong. In fact I'm not sure why we are creating a collection by default in the first place. Seems like this should be a required option.

Can you clarify your first comment and we can take it from there?

Thank you!

**Comment by patrixd** [comment]
The version 0.8.1 initialized the collection instance if it was not defined. It allowed avoid errors with the lack of dynamic information. If the collection is initialized by default, in the moment of iterate the items of the collection it won't launch any error and at the same time it won't render anything. I had an error with the **new version** in the next instance when the collection was not defined (line 318):
```
this.collection.each( function( thisModel ) { ... } )
```
The version 0.8.1 initialized the collection in the initialize method of  Backbone.CollectionView (line 84):
```
_.each(kAllowedOptions, function (option) {
    _this[option] = options[option];
});
if (!this.collection) this.collection = new Backbone.Collection();
```
I can review all the code and check if the attribute of the model with the collection data is defined, but I'm not sure If I will have the same problem in the future. My app is huge and I don't like to have potential errors sources. What do you think? 

Thanks a lot for your quick asistance. If you think initialize the collection by default is not a good practice, I will take the risk.  Even so I think initialize it by default inside Backbone.CollectionView won't be a problem.

**Comment by dgbeck** [comment]
OK in the interest of backwards compatibility we'll go with the original behavior of creating the collection in `initialize` when one does not exist. This changed pushed in v0.11.6, recently published to npm.

Thanks @patrixd for pointing out this issue!
