### ISSUE TITLE
Scrolling and view removal

### ISSUE THREAD

**Issue by edwh** [rotundasoftware/backbone.collectionView#64]
Thanks for this useful bit of code.

Suppose I have a view which is taller than the screen.  I have a button near the bottom of the view, which when I click it, does something which will modify the collection and remove the associated model.  The corresponding view then disappears, and the next view moves up - as you'd expect.

However I was scrolled to the bottom of the view which has now gone, and I am left scrolled down within the view which has now moved up.  Is there a nice way to ensure that when a view is removed, I can scroll to the top of the next view that slides up?

**Comment by dgbeck** [comment]
Hi @edwh ! My bending my brain to try to get my head around this issue but I'm having a hard time visualizing it. Also going off what I do understand, this might not be a collection view issue. If you have some screenshots you can post that would be helpful in figuring out what is going on. Thx!

**Comment by edwh** [comment]
I'll do a fiddle tomorrow - should probably have done that anyway, it's a bit hard to describe.

**Comment by edwh** [comment]
Try https://jsfiddle.net/edwh/jpvogfyt/ - you should be able to see what I
mean.  You have to scroll down to the click me, then click it, at which
point you're left in the middle of the next view whereas I would like to
scroll to the top of it.  I'm not saying that this should always happen,
but I'd like to know the best way for me to achieve it in this case.

**Comment by dgbeck** [comment]
Hi @edwh .. I'm seeing some errors and no output when I load the js fiddle. See screenshot below. Are you able to load this without any errors? What browser?

![image](https://cloud.githubusercontent.com/assets/1483694/10916033/5bcc2b6c-820e-11e5-80b8-4e3adbbee956.png)

**Comment by edwh** [comment]
Sorry, I hadn't saved the last version.  Try again?

https://jsfiddle.net/edwh/jpvogfyt/1/

**Comment by dgbeck** [comment]
Hi @edwh ,

Okay, I see. This issue does not seem to me in the scope of what backbone collection view should do for you, so you will need to create your own logic if you want this behavior. Here is a function that we use at times (es6) to scroll the collection view to the selected model view. Maybe you can repurpose this for what you need:

```
	scrollToFirstSelectedModelView() {
		let selectedView = this.getSelectedModel( { by : 'view' } );
		if( ! selectedView ) return;

		let selectedViewEl = selectedView.$el;

		let scrollTop = this.$el.scrollTop();
		let scrollBottom = scrollTop + this.$el.height();

		let selectedViewTopOffset = selectedViewEl.offset().top - this.$el.offset().top + scrollTop;
		let selectedViewBottomOffset = selectedViewTopOffset + selectedViewEl.height();

		let newScroll;
		if( selectedViewTopOffset < scrollTop ) newScroll = selectedViewTopOffset;
		else if( selectedViewBottomOffset > scrollBottom ) newScroll = selectedViewBottomOffset - this.$el.height() + selectedViewEl.height();

		if( ! _.isUndefined( newScroll ) ) this.$el.scrollTop( newScroll );
	},
```

Hope that helps a little. I'm gonna close this issue since it is not in scope of bb collection view itself.
