### ISSUE TITLE
Compatible with Backbone 1.2.*?

### ISSUE THREAD

**Issue by DriesVandermeulen** [rotundasoftware/backbone.collectionView#65]
Hi,
I really like your Backbone libraries. Quick question though. Using Browserify, I require the latest version of Backbone. Currently, when I hook everything up, I need to manually add JQuery and Courier to the older version of backbone required by CollectionView. 

```javascript
require('bb-collection-view/node_modules/backbone/index.js').$ = $;
require('bb-collection-view/node_modules/backbone/index.js').Courier = Courier;
require('bb-collection-view')
```
As you can imagine, I don't like having 2 version of Backbone floating around. Would this lib work if I upgrade it to Backbone 1.2.*?  I don't have much that much Backbone experience so I do not see the potential breaking changes. Or is there a cleaner workaround to this?
Same question goes for ViewOptions...

**Comment by DriesVandermeulen** [comment]
Saw the version bumb, everything still works like a charm! Thx

**Comment by dgbeck** [comment]
Great, thanks for the heads up! Glad you are enjoying the libraries!
