### ISSUE TITLE
Not maintaining order when multiple models added simultaneously

### ISSUE THREAD

**Issue by edwh** [rotundasoftware/backbone.collectionView#69]
Thanks for this useful tool.

I think there's an issue with this bit of code:

                if( ! _.isUndefined( atIndex ) && atIndex >= 0 && atIndex < parentElOrDocumentFragment.children().length )
                // note this.collection.length might be greater than parentElOrDocumentFragment.children().length here
                    parentElOrDocumentFragment.children().eq( atIndex ).before( thisModelViewWrapped );
                else
                    parentElOrDocumentFragment.append( thisModelViewWrapped );

If multiple models are added to the collection simultaneously, which can happen in a fetch, then we may get two add events for models which both have collection indexes greater than the current length of the DOM structure.  This means we'll always go through the second arm of code, but the result can be that we add the views in the wrong order.

You should be able to see this in the demo here: https://jsfiddle.net/3q58f3Lx/1/

I've not tried to fix this yet, in case I'm missing something.

**Comment by edwh** [comment]
I did a quick and dirty fix which is ok for my purposes (code below).

This saves away the model using data(), and then loops through the children doing an indexOf of the model on the collection to find where to insert.  

I'm concerned about the scalability of this, though, and saving off the model feels hacky - you may already have a better way to do it within your code.

       _insertAndRenderModelView : function( modelView, parentElOrDocumentFragment) {
            var thisModelViewWrapped = this._wrapModelView( modelView );
            $(thisModelViewWrapped).data('collectionViewModel', modelView.model);

            if( parentElOrDocumentFragment.nodeType === 11 ) // if we are inserting into a document fragment, we need to use the DOM appendChild method
                parentElOrDocumentFragment.appendChild( thisModelViewWrapped.get( 0 ) );
            else {
                // We don't really know which of the models in the collection are currently present in our DOM,
                // because add events can happen in strange orders, so we loop through the ones we have comparing
                // the models.
                var inserted = false;
                var modind = this.collection.indexOf(modelView.model);
                var self = this;

                parentElOrDocumentFragment.children().each(function() {
                    if (!inserted) {
                        var thisind = self.collection.indexOf($(this).data('collectionViewModel'));
                        if (thisind > modind) {
                            $(this).before(thisModelViewWrapped);
                            inserted = true;
                        }
                    }
                })

                if (!inserted) {
                    parentElOrDocumentFragment.append( thisModelViewWrapped );
                }
            }

            // we have to render the modelView after it has been put in context, as opposed to in the

**Comment by dgbeck** [comment]
Hi @edwh! Thanks for the fiddle. That was extremely helpful.

So this was kind of a weird case where are hands are tied by the information we get from the `add` event, which is, well, not that much. What we ended up doing is making a note that we need to re-render the collection view if we detect that a modelView should be added at some index that is not yet available.

https://github.com/rotundasoftware/backbone.collectionView/commit/00d557f126f4c39b9f843d3c8a30df33c2d50bb0

Not very pretty but it gets the job done. Published as v1.0.5.

Thanks very much for this report and the recipe to reproduce.

**Comment by edwh** [comment]
Glad that was helpful.  Thanks again for the code.

------ Original Message ------
