### ISSUE TITLE
Effects when adding/removing

### ISSUE THREAD

**Issue by edwh** [rotundasoftware/backbone.collectionView#73]
I'd like items to fade in/out of my collection view.  I can do the fade in within the view render.  I'm not sure how to do the fade out, though - any suggestions?

**Comment by dgbeck** [comment]
Hi @edwh !

I would think that you would need to implement your own logic somewhere to look up the modelView in the collectionView's viewManager, then fade it out, then remove it after that time has passed.

Something like (untested)

```
function fadeAndRemoveModel( collectionView, model ) {
  var modelView = collectionView.viewManager.findByModel( model );
  modelView.$el.fadeOut( 100, function() {
    collectionView.collection.remove( model );
  } );
}
```

Clearly there are lots of ways to implement the fade, not just with the [jquery fadeOut method](http://api.jquery.com/fadeout/), but that is the general idea.

Hope that is helpful.

Dave

**Comment by edwh** [comment]
It's easy if I am removing individual models manually, but I also want to handle the case where models have been removed on the server and this shows up when I refetch the whole collection.
