### ISSUE TITLE
Removing views

### ISSUE THREAD

**Issue by edwh** [rotundasoftware/backbone.collectionView#74]
I'm not sure whether this is a bug or I'm using it wrongly.

I have views which have a tagName of li, and I invoke CollectionView on a ul, and my views are rendered nicely as lis below the ul.  

Now something happens and I remove a model model from the collection.  What then happens is that I then go through this line of code:

if( this._isRenderedAsList() ) modelView.$el.parent().remove(); // Remove the li wrapper from the DOM

...which removes the parent, i.e. the ul, and hence all the peers.  If I comment out that line, it removes just the relevant view, which is what I'm wanting to happen.

If this isn't clear, let me know, and I'll do a fiddle.

**Comment by dgbeck** [comment]
Hi @edwh !

What version of are you using? I believe this issue was already reported and fixed a few months ago.

If you are using the most recent version, can you please link to the line of code you pasted above?

Thanks

**Comment by edwh** [comment]
I'm silly for not trying the latest version.  Thanks.

------ Original Message ------

**Comment by dgbeck** [comment]
=) No problem, thx for stopping by.
